SEED = 42
EPOCHS = 15
LEARN_RATE = 1e-3
IMG_W = 28
IMG_H = 28
IMG_CHANNELS = 1
LATENT_SPACE_DIM = 64
assert LATENT_SPACE_DIM in range(2,128)
N_COMPONENTS_VIEW = 3
assert N_COMPONENTS_VIEW <= LATENT_SPACE_DIM
STATIC_ROOT = "./static"
BATCH_SIZE = 128
LIMIT_SAMPLES = 2000
N_SAMPLES = 8